FROM python:3.10-slim
WORKDIR /app

# Устанавливаем шрифты Microsoft (включая Calibri / Arial) и утилиты для скачивания
RUN apt-get update && apt-get install -y wget curl cabextract xfonts-utils && \
    wget http://ftp.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb && \
    dpkg -i ttf-mscorefonts-installer_3.8_all.deb && \
    rm ttf-mscorefonts-installer_3.8_all.deb && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "-u", "main.py"]
